spring:
  profiles:
    active: development
UniqueCodeUrl: http://unique-code/nologin/uniqueCode
ProductListUrl: http://product/v1/on/list
ToolsUrl: http://tools/nologin/makeJsonFile
DepartmentUrl: http://seller/saa/v1/department/list/ids
ProductSaveOrUpdateESUrl: http://product/v1/saveOrUpdateEs
---
spring:
  profiles: development
#  mvc:
#    view:
#      prefix: classpath:/templates/
#  resources:
#    static-locations: classpath:/static/
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
#    url: jdbc:oracle:thin:@db.openec.zyhao.com:1521/orcl
#    username: info
#    password: 3g2win.com
    url: jdbc:mysql://db.openec.zyhao.com:3306/quartzdb
    username: root
    password: 3g2win.com
    initialize: false
security:  
  basic:
    enabled: false
  oauth2:
    resource:
      userInfoUri: http://user.openec.zyhao.com:8181/uaa/user
    client:
      client-id: acme
      access-token-uri: http://user.openec.zyhao.com:8787
  ignored: /**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery.openec.zyhao.com:8761/eureka/
server:
  jsp-servlet:
    class-name: org.apache.jasper.servlet.JspServlet
management:
  security:
    enabled: false
#LOG
logging:
  config: classpath:log4j2.xml